global using NUnit.Framework;
global using Microsoft.EntityFrameworkCore;
global using SchoolMealsOrderingSystem.Core.Models.Child;
global using SchoolMealsOrderingSystem.Core.Services;
global using SchoolMealsOrderingSystem.Data.Entities;
global using SchoolMealsOrderingSystem.Tests.Mocks;
global using static SchoolMealsOrderingSystem.Data.Constants.ParentUserConstants;
global using static SchoolMealsOrderingSystem.Data.Constants.ChildConstants;
global using static SchoolMealsOrderingSystem.Data.Constants.SchoolUserConstants;
global using static SchoolMealsOrderingSystem.Data.Constants.MainDishConstants;
global using static SchoolMealsOrderingSystem.Data.Constants.GeneralConstants;
global using static SchoolMealsOrderingSystem.Data.Constants.DessertConstatnts;
global using static SchoolMealsOrderingSystem.Data.Constants.SoupConstants;
global using static SchoolMealsOrderingSystem.Data.Constants.RoleConstants;
global using SchoolMealsOrderingSystem.Core.Models.Meal;
global using SchoolMealsOrderingSystem.Data.Entities.Meals;
global using SchoolMealsOrderingSystem.Data.Entities.Menu;